# filebeat/filebeat.yml

filebeat.inputs:
- type: filestream
  id: spring-boot-logs
  enabled: true
  paths:
    - /logs/*.log
  fields:
    type: spring-boot
  fields_under_root: true

# Template 설정 추가
setup.template.name: "spring-logs"
setup.template.pattern: "spring-logs-*"
setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

# Elasticsearch 출력 설정
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "spring-logs-%{+yyyy.MM.dd}"

# Kibana 설정
setup.kibana:
  host: "kibana:5601"

# Logging 설정
logging.level: debug
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644

# 프로세서 설정
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~