# /Users/summerlee/fisa/pj-airflow/monitoring-docker-compose.yml


services:
  statsd-exporter:
    image: prom/statsd-exporter:latest

    command:
    - "--statsd.mapping-config=/tmp/statsd_mapping.yml"
    volumes:
    - /Users/summerlee/fisa/pj-airflow/statsd_mapping.yml:/tmp/statsd_mapping.yml
    networks:
      - afml-network
    ports:
      - "9102:9102"
      - "9125:9125/udp"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /Users/summerlee/fisa/pj-airflow/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    cap_add:
      - NET_RAW
    networks:
      - afml-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - afml-network


networks:
 afml-network:
    name: afml-network
    external: true


volumes:
  prometheus_data:
  grafana_data: